{% set build = 4 %}
{% set name = "paraprobe" %}
{% set version = "v0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.com/{{ name }}/{{ name }}-toolbox/-/archive/{{ version }}/{{ name }}-toolbox-{{ version }}.tar.gz
    sha256: ded5193f54f6aa63fea3092f0cf8a680d2ad96501936e830ef1ba7f298595577
    folder: paraprobe-toolbox
    patches:
      - paraprobe.patch
 
build:
  number: {{ build }}
  skip: true  # [not linux]
  #skip: True  # [osx]
  #skip: True  # [py<38] 

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - git
    - m4
    - libgomp      # [linux]
    - llvm-openmp  # [osx]

  host:
    - python
    - cython
    - setuptools
    - {{ mpi }}
    - gmp
    - mpfr
    - libhwloc
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - tetgen
    - fftw
    - boost =1.78.0
    - boost-cpp =1.78.0
    - eigen 
    - voro
    - cgal =5.5.1
    - cgal-cpp =5.5.1
    - libaec
    - numpy >=1.17
    - libzlib =1.2.13
  run:
    - python
    - setuptools
    - scikit-learn =1.0.2
    - ase =3.22.1
    - ipywidgets =7.6.3
    - h5py 
    - jupyterlab[full] =3.0.0
    - punx =0.3.0
    - nexpy =0.14.4
    - silx[full] =1.0.0
    - numpy >=1.17
    - gitpython
    - pandas
test:
  imports:
    - paraprobe_parmsetup
    - paraprobe_transcoder
  #commands:
  #  - paraprobe_ranger 636502001 PARAPROBE.Ranger.Config.SimID.636502001.nxs

about:
  home: https://gitlab.com/paraprobe/paraprobe-toolbox
  summary: 'Paraprobe Tools'
  license: GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - VORO_LICENSE
  doc_url: https://gitlab.com/paraprobe/paraprobe-toolbox
  dev_url: https://gitlab.com/paraprobe/paraprobe-toolbox

extra:
  recipe-maintainers:
    - srmnitc
